-- Phase 9 배치 (FSD §12).
-- Spring Batch 메타데이터도 Flyway가 소유한다. Boot 자동 초기화는 application.yml에서 끈다.

CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

-- INV-1~6은 성공 결과도 모두 남긴다. 그래야 "검사하지 않음"과 "검사 후 정상"을 구분할 수 있다.
CREATE TABLE reconciliation_result (
    id                 BIGSERIAL    PRIMARY KEY,
    job_execution_id   BIGINT       NOT NULL REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID),
    run_date           DATE         NOT NULL,
    token_symbol       VARCHAR(50)  NOT NULL DEFAULT '*', -- '*'는 INV-4/6 전역 검사
    invariant_code     VARCHAR(10)  NOT NULL CHECK (invariant_code IN
                                      ('INV-1', 'INV-2', 'INV-3', 'INV-4', 'INV-5', 'INV-6')),
    valid              BOOLEAN      NOT NULL,
    expected_value     NUMERIC(38, 0),
    actual_value       NUMERIC(38, 0),
    difference_value   NUMERIC(38, 0),
    first_mismatch_seq BIGINT,
    checked_count      BIGINT,
    detail             TEXT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_reconciliation_job_scope
        UNIQUE (job_execution_id, token_symbol, invariant_code)
);

CREATE INDEX idx_reconciliation_run_date
    ON reconciliation_result (run_date DESC, invariant_code, valid);
CREATE INDEX idx_reconciliation_violation
    ON reconciliation_result (valid, created_at DESC);

-- Phase 10 운영 화면이 배치 이력을 재집계하지 않고 그대로 조회할 수 있는 일별 스냅샷.
CREATE TABLE settlement_report (
    report_date      DATE          PRIMARY KEY,
    execution_count BIGINT        NOT NULL,
    execution_amount NUMERIC(38,0) NOT NULL,
    buy_fee          NUMERIC(38,0) NOT NULL,
    sell_fee         NUMERIC(38,0) NOT NULL,
    total_fee        NUMERIC(38,0) NOT NULL,
    job_execution_id BIGINT        NOT NULL REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- 90일 경과 API 로그는 원본 ID를 보존해 재실행 시 중복 아카이브를 막는다.
CREATE TABLE api_call_log_archive (
    original_id      BIGINT       PRIMARY KEY,
    client_id        VARCHAR(64)  NOT NULL,
    endpoint         VARCHAR(255) NOT NULL,
    method           VARCHAR(10)  NOT NULL,
    status_code      INT          NOT NULL,
    latency_ms       BIGINT       NOT NULL,
    idempotency_key  VARCHAR(100),
    body_hash        CHAR(64),
    called_at        TIMESTAMPTZ  NOT NULL,
    archived_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    job_execution_id BIGINT       NOT NULL REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE INDEX idx_api_call_log_archive_called
    ON api_call_log_archive (called_at DESC);
